# Generated by Django 6.0.4 on 2026-04-08 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='POSCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('OPEN', 'Open Session'), ('OCCUPY', 'Occupy'), ('RELEASE', 'Release'), ('CLOSE', 'Close'), ('STATUS', 'Status'), ('CHANGE', 'Change'), ('RESET', 'Reset'), ('CANCEL', 'Cancel')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LOCKED', 'Locked'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('DEAD', 'Dead Letter')], default='PENDING', max_length=20)),
                ('lock_owner', models.CharField(blank=True, max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('result_code', models.CharField(blank=True, max_length=20)),
                ('result_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_api.pos')),
            ],
        ),
    ]
