# Generated by Django 6.0.4 on 2026-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poscommand',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Amount in cents. Positive = deposit, negative = dispense.', null=True),
        ),
        migrations.AlterField(
            model_name='poscommand',
            name='command',
            field=models.CharField(choices=[('OPEN', 'Open Session'), ('OCCUPY', 'Occupy'), ('RELEASE', 'Release'), ('CLOSE', 'Close'), ('STATUS', 'Status'), ('CHANGE', 'Change (Deposit / Dispense)'), ('RESET', 'Reset'), ('CANCEL', 'Cancel')], max_length=20),
        ),
    ]
